In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# ENABLE IF USING COLAB
USE_COLAB = True

if USE_COLAB:
    import os
    from google.colab import drive
    
    FOLDERNAME = 'UMass_Amherst/NN_AMI/NN_Project'
    drive.mount('/content/drive')
    %cd /content/drive/My\ Drive/$FOLDERNAME

    if os.path.exists('./spectroconv/'):
      %cd ./spectroconv
      !pip install hub
      !pip install hub[audio]
      !pip install wandb
    else:
      print("Error, must first pull project repository from github to Drive using ColabGitCommands.ipynb")

Mounted at /content/drive
/content/drive/My Drive/UMass_Amherst/NN_AMI/NN_Project
/content/drive/My Drive/UMass_Amherst/NN_AMI/NN_Project/spectroconv
     |████████████████████████████████| 348 kB 12.5 MB/s 
     |████████████████████████████████| 132 kB 55.3 MB/s 
     |████████████████████████████████| 6.2 MB 22.6 MB/s 
     |████████████████████████████████| 81 kB 10.3 MB/s 
     |████████████████████████████████| 8.7 MB 40.5 MB/s 
     |████████████████████████████████| 79 kB 8.7 MB/s 
     |████████████████████████████████| 138 kB 53.9 MB/s 
     |████████████████████████████████| 65 kB 3.2 MB/s 
     |████████████████████████████████| 127 kB 51.5 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

In [3]:
import torch
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Mon May  2 06:10:38 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
from models import wb_experiment

NumExpr defaulting to 2 threads.


In [31]:
n_mels = 128
wb_config = {
    'project': 'spectroconv-debug',
    'entity': 'jakeval-colab',
    'group': 'cnn', # use this only when training/evaluating/etc a CNN
}

config = {
    'data': {
        'train': {
            'name': f'nsynth-full-{n_mels}-train'
        },
        'val': {
            'name': f'nsynth-full-{n_mels}-val'
        }
    },
    'model': {
        'id': wb_experiment.ModelType.Taenzer,
        'name': 'Taenzer'
    },
    'logging': {
        'batch_log_interval': 250,
        'eval_every_batch': True,
        'eval_every_epoch': True,
    },
    'parameters': {
      'epochs': 5,
      'batch_size': 124, # Taenzer setting
      'optimizer': 'adam', # Taenzer setting
      'learning_rate': 0.0001, # Taenzer setting
      'dropout': 0.25, # Taenzer setting
      'l2_reg': 0.0000, # Taenzer setting
      'kernel_size': 3, # Taenzer setting
      'num_channels': 32, # Taenzer setting
      'num_conv_layers': 4, # Taenzer setting
      'linear_layer_size': 1024, # Taenzer setting
    },
}

trainer = wb_experiment.TrainExperiment(wb_config=wb_config, login_key=True)
trainer.run_train(config, save_model=False)


wandb: WARNING Calling wandb.login() after wandb.init() has no effect.


hub://jakeval/nsynth-full-128-train-metadata loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/jakeval/nsynth-full-128-train-metadata
hub://jakeval/nsynth-full-128-train loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/jakeval/nsynth-full-128-train
hub://jakeval/nsynth-full-128-val-metadata loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/jakeval/nsynth-full-128-val-metadata
hub://jakeval/nsynth-full-128-val loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/jakeval/nsynth-full-128-val
input shape (128, 71)


  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/1171 [00:00<?, ?it/s]

-1 torch.Size([124, 1, 128, 71])
0 tensor(16.3253, device='cuda:0')
1 torch.Size([124, 1, 128, 71])
2 tensor(16.3253, device='cuda:0')
3 torch.Size([124, 1, 128, 71])
4 tensor(29.8897, device='cuda:0')
Batch 0: Loss: 2.0817,	Accuracy: 0.1694
======VAL========
-1 torch.Size([124, 1, 128, 71])
0 tensor(601378.2500, device='cuda:0')
1 torch.Size([124, 1, 128, 71])
2 tensor(601378.2500, device='cuda:0')
3 torch.Size([124, 1, 128, 71])
4 tensor(623765.5625, device='cuda:0')
======VAL========
-1 torch.Size([124, 1, 128, 71])
0 tensor(611270.3750, device='cuda:0')
1 torch.Size([124, 1, 128, 71])
2 tensor(611270.3750, device='cuda:0')
3 torch.Size([124, 1, 128, 71])
4 tensor(634025.9375, device='cuda:0')
======VAL========
-1 torch.Size([124, 1, 128, 71])
0 tensor(599808.4375, device='cuda:0')
1 torch.Size([124, 1, 128, 71])
2 tensor(599808.4375, device='cuda:0')
3 torch.Size([124, 1, 128, 71])
4 tensor(622137.3125, device='cuda:0')
======VAL========
-1 torch.Size([124, 1, 128, 71])
0 tensor(60

AttributeError: ignored

In [6]:
n_mels = 128
wb_config = {
    'project': 'spectroconv-debug',
    'entity': 'jakeval-colab',
    'group': 'cnn' # use this only when training/evaluating/etc a CNN
}

config = {
    'data': {
        'train': {
            'name': f'nsynth-full-{n_mels}-train'
        },
        'val': {
            'name': f'nsynth-full-{n_mels}-val'
        }
    },
    'model': {
        'id': wb_experiment.ModelType.CNN,
        'name': 'CNN'
    },
    'logging': {
        'batch_log_interval': 250,
        'eval_every_batch': True,
        'eval_every_epoch': True,
    },
    'parameters': {
      'epochs': 5,
      'batch_size': 80,
      'optimizer': 'adam',
      'learning_rate': 0.0008,
      'dropout': 0.5, # probability of an element to be zeroed (0 = no dropout)
      'l2_reg': 0.0005,
      'kernel_size': 3,
      'num_channels': 32,
      'num_conv_layers': 1,
      'linear_layer_size': 100,
    },
}

In [ ]:
trainer = wb_experiment.TrainExperiment(wb_config=wb_config, login_key=True)
trainer.run_train(config, save_model=False)

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


hub://jakeval/nsynth-full-128-train-metadata loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/jakeval/nsynth-full-128-train-metadata
hub://jakeval/nsynth-full-128-train loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/jakeval/nsynth-full-128-train
hub://jakeval/nsynth-full-128-val-metadata loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/jakeval/nsynth-full-128-val-metadata
hub://jakeval/nsynth-full-128-val loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/jakeval/nsynth-full-128-val
CNN last layer h: 64 w 35 channels: 32


  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/1814 [00:00<?, ?it/s]

Batch 0: Loss: 1.6506,	Accuracy: 0.1625
scores		y
tensor([[ -2895.9404,  29757.3848,  18830.7031, -16687.5820,   5211.6035],
        [  2483.8123,  28146.3203,  -2702.4985,  -9287.0449,  -4066.9092],
        [  -365.0234,    470.1609,    185.4688,   -156.7252,    246.8656],
        [ -1550.3760,  25504.5801,  11248.7490, -13210.4678,  15905.6875],
        [-51024.5469,  31852.2871, 116243.8594, -30384.8594,  -5446.3706]],
       device='cuda:0') 
 [1 1 4 1 2] 
 [[1]
 [1]
 [1]
 [1]
 [2]] 
 [0.         0.53846154 0.52       0.         0.        ]
Split: val, Loss: 18996.18,	Accuracy: 0.3838,	F1: 0.2305
Batch 250: Loss: 0.9278,	Accuracy: 0.5756
scores		y
tensor([[-4.4656e+04,  8.7397e+04, -3.1458e+01, -5.9213e+04,  7.9732e+04],
        [-2.5857e+04,  1.2488e+05, -3.6293e+04, -1.0775e+05, -3.1702e+04],
        [-2.8427e+04,  2.1373e+04,  4.8154e+03, -1.2713e+04,  3.9865e+04],
        [-6.1334e+04,  7.1014e+04, -3.4271e+04, -8.1182e+04,  6.9356e+04],
        [-2.8064e+05,  2.2949e+05,  1.70

  0%|          | 0/1814 [00:00<?, ?it/s]

Batch 0: Loss: 0.6899,	Accuracy: 0.7687
scores		y
tensor([[-162186.7812,  243577.8281,   88638.1250, -192412.5000,  190118.9375],
        [-140168.3750,  361721.6250,  156671.8750, -170110.0000,  124640.8281],
        [ -66122.4688,   56813.1641,    2298.9163,  -37630.5625,   73243.1953],
        [-170335.2188,  175368.1719,  117341.2812,  -95747.1484,  135337.1562],
        [-552156.5625,  249956.4062,  215669.2656,  -15397.0762,  273191.1562]],
       device='cuda:0') 
 [1 1 4 1 2] 
 [[1]
 [1]
 [4]
 [1]
 [4]] 
 [0.83333333 0.65517241 0.8125     0.66666667 0.57142857]
Split: val, Loss: 25624.54,	Accuracy: 0.6218,	F1: 0.5953


KeyboardInterrupt: ignored

In [ ]:
# untested

config = {
    'data': {
        'val': {
            'name': f'nsynth-full-{n_mels}-val'
        }
    },
    'model_name': 'CNN',
    'eval': {
        'examples': {
            'k': 8
        }
    }
}


In [ ]:

trainer = wb_experiment.EvalExperiment(wb_config)
metrics, examples_df = trainer.run_evaluate(config)

## Train on the full dataset

In [ ]:
# Wandb should take care of plotting for us?

'''
from matplotlib import pyplot as plt
fig, ax = plt.subplots()
ax.plot(losses)
fig, ax = plt.subplots()
ax.plot(train_accuracies, label='train acc')
ax.plot(val_accuracies, label='val acc')
ax.plot(val_f1s, label='val f1')
ax.legend()
plt.savefig("learning_metrics.png")
plt.show()
'''

In [ ]:
#print(train_model.stream_accuracy(clf, dl_val, device))

0.7415788789179347


In [ ]:
#print(train_model.stream_f1(clf, dl_val, device))

0.7109029348873568
